pipeline:
    name: $pipelineName
    identifier: $pipelineIdentifier
    projectIdentifier: $projectIdentifier
    orgIdentifier: $orgName
    tags: {}
    stages:
        - stage:
              name: test
              identifier: test
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceDefinition:
                          spec:
                              artifacts:
                                  sidecars: []
                                  primary:
                                      type: DockerRegistry
                                      spec:
                                          connectorRef: $dockerConnectorName
                                          imagePath: library/nginx
                                          tag: stable-perl
                              manifestOverrideSets: []
                              manifests:
                                  - manifest:
                                        identifier: values
                                        type: Values
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: $gitHubConnectorName
                                                    gitFetchType: Branch
                                                    paths:
                                                        - manifests/blue-green/perf-values.yaml
                                                    branch: master
                                  - manifest:
                                        identifier: masnifest_k8s
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: $gitHubConnectorName
                                                    gitFetchType: Branch
                                                    paths:
                                                        - manifests/basic/templates/spec.yaml
                                                    branch: master
                                            skipResourceVersioning: false
                              variables: []
                          type: Kubernetes
                      serviceRef: $svcName
                  infrastructure:
                      environmentRef: QA
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: $k8sConnectorName
                              namespace: <+input>
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                      infrastructureKey: ""
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                          - step:
                                type: K8sDelete
                                name: delete-deployment
                                identifier: deletedeployment
                                spec:
                                    deleteResources:
                                        type: ReleaseName
                                        spec:
                                            deleteNamespace: false
                                timeout: 10m
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              variables:
                  - name: resourceNamePrefix
                    type: String
                    value: <+input>
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
