pipeline:
    identifier: $pipelineIdentifier
    properties:
        ci:
            codebase:
                build:
                    type: branch
                    spec:
                        branch: master