pipeline:
  name: $identifier
  identifier: $identifier
  projectIdentifier: $projectIdentifier
  orgIdentifier: $orgIdentifier
  tags: {}
  delegateSelectors:
    - $delegate
  properties:
    ci:
      codebase:
        connectorRef: $gitConnectorRef
        build: <+input>
  stages:
    - stage:
        name: Stage1
        identifier: Stage1
        description: ""
        type: CI
        strategy:
          parallelism: 1
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  strategy:
                    parallelism: 5
                  spec:
                    connectorRef: $dockerConnectorRef
                    image: alpine
                    shell: Sh
                    command: |-
                      sleep 100
                      export abc=xyz
                      echo "text secret is: " <+secrets.getValue("account.user0")>
                      echo "abc"
                    outputVariables:
                      - name: abc
                    imagePullPolicy: IfNotPresent
                    resources:
                      limits:
                        memory: 10M
                        cpu: 10m
              - step:
                  name: Run_2
                  identifier: Run_2
                  template:
                    templateRef: $templateRef
                    versionLabel: $versionLabel
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: $k8sConnectorRef
              namespace: $namespace
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
