pipeline:
  name: $identifier
  identifier: $identifier
  projectIdentifier: $projectIdentifier
  orgIdentifier: $orgIdentifier
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: $gitConnectorRef
        build: <+input>
  stages:
    - stage:
        name: Stage1
        identifier: Stage1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  strategy:
                    parallelism: 2
                  spec:
                    connectorRef: $dockerConnectorRef
                    image: alpine
                    shell: Sh
                    command: |-
                      sleep 70
                      export abc=xyz
                    outputVariables:
                      - name: abc
                    resources:
                      limits:
                        memory: 10M
                        cpu: 10m
              - step:
                  name: Run_2
                  identifier: Run_2
                  type: Run
                  spec:
                    connectorRef: $dockerConnectorRef
                    image: alpine
                    shell: Sh
                    command: |-
                      total_time=70
                      interval=1
                      counter=0
                      
                      while [ $counter -lt $total_time ]; do
                          echo "abc"
                          sleep $interval
                          counter=$((counter + $interval))
                      done
                    resources:
                      limits:
                        memory: 10M
                        cpu: 10m
                  strategy:
                    parallelism: 2
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: $k8sConnectorRef
              namespace: $namespace
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux