trigger:
  name: $identifier
  identifier: $identifier
  enabled: true
  encryptedWebhookSecretIdentifier: ""
  description: ""
  tags: {}
  orgIdentifier: $orgIdentifier
  stagesToExecute: []
  projectIdentifier: $projectIdentifier
  pipelineIdentifier: $pipelineIdentifier
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: PullRequest
        spec:
          connectorRef: $connectorRef
          autoAbortPreviousExecutions: false
          payloadConditions:
            - key: <+trigger.payload.zen>
              operator: Equals
              value: $payloadConditionValue
          headerConditions: []
          actions: []
  pipelineBranchName: master
  inputSetRefs:
    - $inputSetRefs
